### ISSUE TITLE
Approche zones manquantes

### ISSUE THREAD

**Issue by ThomasG77** [guillaumerose/openmaptiles-generateur-france#1]
A priori, pour les cas mentionnés https://github.com/guillaumerose/openmaptiles-generateur-france/blob/master/run.sh#L70, une recette possible https://github.com/openmaptiles/openmaptiles/issues/485#issuecomment-409605790

Le but est de discuter de l'approche pour gérer ces cas ultra-marins

- Saint-Martin, prendre https://download.geofabrik.de/central-america-latest.osm.pbf et reste à déterminer l'étendue de découpage https://www.openstreetmap.org/?mlat=18.075277777778&mlon=-63.06&zoom=7#map=11/18.0568/-63.0897
- Saint-Barthélemy, même fichier que Saint-Martin
- Saint-Pierre-et-Miquelon prendre https://download.geofabrik.de/north-america/canada-latest.osm.pbf
- Analyse sur Terres australes et antarctiques françaises en cours car îles très éloignées les unes des autres donc nécessitant plusieurs pbf

Potentiellement, soumettre une proposition de polygones pour ces territoires à Geofabrik. Fichiers de type poly (https://wiki.openstreetmap.org/wiki/Osmosis/Polygon_Filter_File_Format) comme https://download.geofabrik.de/north-america/canada.poly

Trouvables sur la partie "Other Formats and Auxiliary Files" de https://download.geofabrik.de/north-america/canada.html par exemple

PS: prêt à prendre du temps pour aider

**Comment by guillaumerose** [comment]
Je viens tout juste d'ajouter les 3 premiers via https://github.com/guillaumerose/openmaptiles-generateur-france/commit/f6ca002a9b2f34ff62feee34fada90f719cd979a. 

J'ai fait une bbox autour des îles moi-même. J'espère que c'est bon. 

Le rendu est dispo ici: https://tiles.guillaumerose.fr/ 

Je vais refaire tourner depuis 0 cette nuit pour être sur que c'est bon. La Polynésie et la Nouvelle-Calédonie prennent un temps incroyable (à cause de l'étendue)...

**Comment by ThomasG77** [comment]
Pour les TAAF, il est possible de partir de la relation https://www.openstreetmap.org/relation/2186658#map=3/-30.37/59.94

On va sur https://polygons.openstreetmap.fr/?id=2186658 puis on récupère le poly avec le moins de points.

Les TAAF sont à cheval sur trois extraits de données Geofabrik (cf capture):

- antarctica
- australia-oceania
- africa

![Aperçu TAAF et extraits Geofabrik](https://user-images.githubusercontent.com/642120/149329982-c64ce141-83ca-4b9d-a0f4-e2dfa338ac25.png)


On va assembler les trois zones avant de faire un découpage plutôt que télécharger le "planet" complet, beaucoup trop lourd

```
wget -q -N -i - << EOF https://download.geofabrik.de/antarctica-latest.osm.pbf
https://download.geofabrik.de/africa-latest.osm.pbf
https://download.geofabrik.de/australia-oceania-latest.osm.pbf
EOF
osmium merge africa-latest.osm.pbf australia-oceania-latest.osm.pbf antarctica-latest.osm.pbf -o preprocess-taaf-latest.osm.pbf
wget -O taaf.poly "https://polygons.openstreetmap.fr/get_poly.py?id=2186658&params=0.040000-0.010000-0.010000"
osmium extract --overwrite --polygon taaf.poly -o taaf.osm.pbf preprocess-taaf-latest.osm.pbf
```

**Comment by guillaumerose** [comment]
Le problème de faire la génération sur l'union des osm.pbf est que cela oblige à générer un mbtiles sur une très très grande zone: la bounding box minimum qui englobe taaf.poly.
Par exemple: la Polynésie prend 5-6h pour ne faire que des tuiles d'eau.

Une autre approche serait de faire un mbtiles pour chaque petite île.

**Comment by ThomasG77** [comment]
> Le problème de faire la génération sur l'union des osm.pbf est que cela oblige à générer un mbtiles sur une très très grande zone: la bounding box minimum qui englobe taaf.poly

Pas sûr d'avoir compris, on fait un union des 3 zones, on découpe pour ne garder que les zones découpées. Si l'outil prend effectivement la bounding box même pleine de vide pour générer, comme tu l'avances, ce sera trop long. Je connais les outils openmaptiles mais très longtemps que je n'ai pas regardé le fonctionnement interne.

Dans ce cas, si on veut réduire la zone générée comme proposé avec un par polygone des taaf. Il y a 14 polygons pour les taaf.
La dernière ligne proposée deviendrait alors en partant des fichiers poly en PJ ([taaf.zip](https://github.com/guillaumerose/openmaptiles-generateur-france/files/7873659/taaf.zip))

```
for i in taaf-*.poly;
  do osmium extract --overwrite --polygon $i -o ${i%.*}.osm.pbf preprocess-taaf-latest.osm.pbf
done;
```

Cette méthode pourrait être reprise pour améliorer la vitesse sur la Polynésie et la Nouvelle-Calédonie

L'alternative bis pour ne pas se "trimballer" les fichiers de découpage serait d'avoir l'étendue des 14 îles pour conserver une approche de découpe par étendue dans le cas des taaf et faire pareil pour chacun des cas "lents" e.g Polynésie et Nouvelle-Calédonie

**Comment by guillaumerose** [comment]
La méthode a l'air bonne. Si tu as le temps de faire une PR, ce serait cool !

**Comment by guillaumerose** [comment]
Les TAAF sont dedans. Les tuiles sont à jour sur https://tiles.guillaumerose.fr/.
