### ISSUE TITLE
404

### ISSUE THREAD

**Issue by 2803media** [guillaumerose/openmaptiles-generateur-france#8]
Bonjour Guillaume,

Je constate que votre site est en 404 est ce normal?

Bonne journée

Henri

**Comment by guillaumerose** [comment]
Bonjour,

Oui j'ai coupé le serveur. Les tuiles étaient de toute façon très anciennes. 
Le mieux c'est d'utiliser https://openmaptiles.geo.data.gouv.fr/ - les données sont mises à jour très régulièrement.

**Comment by 2803media** [comment]
Oui effectivement ;)
J'utilise ces tuiles d'ailleurs maintenant https://files.data.gouv.fr/openmaptiles/france-vector.mbtiles
